### PR TITLE
check current branch

### PR DESCRIPTION
**Pull request by gko**
If it's not master then add it to the url

Based on https://github.com/paulirish/git-open behaviour

### CODE REVIEW

**Comment by laixintao** [comment]
I am not sure, when I open a file on GitHub, I want exactly the commit/lines, so I can copy the link share to other people, paste into a PR log.

But if it's a branch, the link could easily be broken.

Maybe we can use a config variable in `.vimrc` and default to commit link? What do you think?

**Comment by ruanyl** [comment]
Hey @gko , thanks for the PR, LGTM. But it seems the URL works for Github and Gitlab but not for Bitbucket. I haven't tried Cgit yet.

**Comment by gko** [comment]
Hi @ruanyl, thanks for the remark.

I rewrote the whole thing. Only `cgit` left.

I also noticed that `bitbucket` actually asks a revision besides `ref_name` which makes no sense.
Example:
https://bitbucket.org/gorodinskiy/test/src/?at=test%23123
this doesn't work

however this does:
https://bitbucket.org/gorodinskiy/test/src/720e03259f40022ee3db10a5ab0314eae220f86b/?at=test%23123

**Comment by gko** [comment]
all done.

I added a `FIXME` (vim doesn't recognize macOS)
https://github.com/gko/vim-gh-line/blob/fcc6927a50ddd3bccb15d20cd475c3efc7cc11bc/plugin/vim-gh-line.vim#L30

but it's an issue a part

**Comment by ruanyl** [comment]
@gko the bitbucket URL seems just like this `https://bitbucket.org/yulongruan/test/src/test-branch/`, like `.../src/<branch_name>`.

**Comment by gko** [comment]
fixed

**Comment by ruanyl** [comment]
@gko Cool! thanks for the PR.

**Pull request merged**
