### PR TITLE
Fix Bitbucket remote url handling and add Gitlab multiline.

### PR DESCRIPTION
**Pull request by vnhnhm**
As the remote from Bitbucket contains the user, followed by an `@`, the url generation it makes doesn't work for showing the file being accessed. I've added a function for removing the user and the at symbol from the url.

Added the support for multilines in Gitlab. It works almost the same way with Bitbucket, just it uses `- ` instead `:`.

I've moved some of the essential parts of the script to single functions to reduce the `gh_line()` one.

### CODE REVIEW

**Comment by ruanyl** [comment]
@vnhnhm thank you for the PR, the refactor of `gh_line()` looks good to me. But bitbucket url , for example `https://user@bitbucket.org/user/repo.git` works for me out of the box, browser redirect to the expected link.

**Comment by vnhnhm** [comment]
Hi @ruanyl, thanks for the feedback.

I was wondering, maybe what browser are you using?. I've tested on Chrome, Safari y Firefox. The first one loads Bitbucket, but isn't able to show me the file; Safari works well without any problem, but Firefox (61.0.2) renders an initial message, that makes me think is what Chrome is facing but without telling anything.

Tested for Bitbucket on three browsers. I leave both screenshots to make you an idea.

screen shot 2018-08-08 at 10 07 04 pm


screen shot 2018-08-08 at 10 13 02 pm

**Comment by ruanyl** [comment]
It looks like the current `url` of bitbucket is incorrect because of the line range. 
And I see the same issue on Firefox. Tested with the PR, it works good to me, will merge now. Thanks :)

**Comment by vnhnhm** [comment]
Thanks!. I'm going to make a new PR for adding the blame url this time.

**Pull request merged**
