### PR TITLE
Make sure colon in the https:// scheme is not replaced

### LINKED ISSUE #16: sed command replaces `https:` with `https/` if remote url is using https scheme.
The sed command looks like [this](https://github.com/ruanyl/vim-gh-line/blob/d6289c8fbef269c465e5cb702cfd10923ccc81c5/plugin/vim-gh-line.vim#L59)

```
" 1. Replace the first `:` with `/`.
    " 2. Strip the `git@` part and replace it with `https://`.
    " 3. Strip the `.git` part in the end.
    let sed_cmd = "sed 's\/:\/\\/\/; s\/^[^@]*@\/https:\\/\\/\/; s\/.git$\/\/; '"
``` 
If the url is something like this 
```
$ git config --get remote.origin.url
https://github.com/ahakanbaba/delve.git
```

The resulting open command launched by vim-gh-line looks like this 
```
open https///github.com/ahakanbaba/delve/blob/fc0d40144a9c65aaf9b851b5816d33f4107f0b75/CHANGELOG.md#L1
```

The 
> Replace the first `:` with `/`.
Has replaced the `:` at the https: scheme of the url and breaks the browser launch. 

I think the intention of that was to replace the separator in remotes using the ssh protocol 
For example 
```
git@gitenterprise.inside-acme.net:acme/repo-check.git
```

But it breaks https urls.

### PR DESCRIPTION
**Pull request by ahakanbaba**
fixes #16

### CODE REVIEW

**Comment by KostyaEsmukov** [comment]
Unfortunately your solution doesn't seem to work on my system with neither GNU nor BSD sed (I expect that the `:` should be turned to `/`):
```
bash-3.2$ echo git@github.com:ruanyl/vim-gh-line.git | gsed 's/(https)\@<!:/\//'
git@github.com:ruanyl/vim-gh-line.git
bash-3.2$ echo git@github.com:ruanyl/vim-gh-line.git | sed 's/(https)\@<!:/\//'
git@github.com:ruanyl/vim-gh-line.git

bash-3.2$ echo git@github.com:ruanyl/vim-gh-line.git | gsed 's/\(https\)\@<!:/\//'
git@github.com:ruanyl/vim-gh-line.git
bash-3.2$ echo git@github.com:ruanyl/vim-gh-line.git | sed 's/\(https\)\@<!:/\//'
git@github.com:ruanyl/vim-gh-line.git
```

Maybe I'm doing the shell/sed escapes wrong? Could you give any reference to the syntax of the negative lookbehind expression for sed that you're using? I couldn't find any.

However, it's possible to avoid lookbehinds completely for this problem by combining 1st and 2nd substitutions:

```
bash-3.2$ echo git@github.com:ruanyl/vim-gh-line.git | gsed 's/^[^@:]*@\([^:]*\):/https:\/\/\1\//'
https://github.com/ruanyl/vim-gh-line.git
bash-3.2$ echo git@github.com:ruanyl/vim-gh-line.git | sed 's/^[^@:]*@\([^:]*\):/https:\/\/\1\//'
https://github.com/ruanyl/vim-gh-line.git

bash-3.2$ echo https://github.com/ruanyl/vim-gh-line.git | sed 's/^[^@:]*@\([^:]*\):/https:\/\/\1\//'
https://github.com/ruanyl/vim-gh-line.git
bash-3.2$ echo https://github.com/ruanyl/vim-gh-line.git | gsed 's/^[^@:]*@\([^:]*\):/https:\/\/\1\//'
https://github.com/ruanyl/vim-gh-line.git
```

PS: It would be nice to set up regression tests and CI for this project (obviously not in this PR, but in general).

**Comment by ahakanbaba** [comment]
Thank you @KostyaEsmukov  for your input. 
I have used the regular expressions you suggested. The need for forward-backward slash escaping is rather unfortunate but I think this should work. It did in my setup.

**Comment by ahakanbaba** [comment]
@ruanyl could you please review this PR ? It is a bugfix and it would be good to merge it sooner than later.

**Comment by ruanyl** [comment]
thank you very much for the pr, works good with Github/Bitbucket https and ssh remote url.

**Pull request merged**
